# Generated by Django 3.2 on 2021-05-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('iduser', models.AutoField(db_column='idUser', primary_key=True, serialize=False)),
                ('nom', models.TextField()),
                ('prenom', models.TextField()),
                ('email', models.TextField(unique=True)),
                ('password', models.TextField()),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
    ]
