# Generated by Django 3.2 on 2021-05-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210502_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
