# Generated by Django 3.2 on 2021-05-05 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
