# Generated by Django 3.0 on 2021-05-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='imageTicket',
            fields=[
                ('idTicket', models.AutoField(db_column='idTicket', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('prob', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('password1', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ticket',
                'managed': True,
            },
        ),
    ]
