# Generated by Django 3.0 on 2021-05-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_imageticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageticket',
            name='password1',
        ),
        migrations.AddField(
            model_name='imageticket',
            name='uriimage',
            field=models.BinaryField(null=True),
        ),
    ]
