# Generated by Django 3.0 on 2021-05-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210512_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageticket',
            name='idUser',
            field=models.IntegerField(null=True),
        ),
    ]
