# Generated by Django 3.0 on 2021-05-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210513_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageticket',
            name='uriimage',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
