# Generated by Django 3.0 on 2021-05-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210513_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageticket',
            name='uriimage',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
