# Generated by Django 3.0 on 2021-05-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210513_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageticket',
            name='uriimage',
            field=models.BinaryField(null=True),
        ),
    ]
