# Generated by Django 3.0 on 2021-05-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210513_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageticket',
            name='uriimage',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
