# Generated by Django 3.0 on 2021-05-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210513_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageticket',
            name='uriimage',
            field=models.TextField(null=True),
        ),
    ]
